openapi: 3.0.0
x-stoplight:
  id: lvz3welklfcai
info:
  title: ReVanced API
  version: '1.0'
  description: |-
    The official ReVanced API, for public use.

    For more information, check our [GitHub organization](https://github.com/revanced) or join our [Discord server](https://revanced.app/discord)!
  license:
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
    name: GPL-3.0
servers:
  - url: 'https://api.revanced.app'
    description: prod
  - url: 'http://localhost:8080'
    description: local
paths: {}
components:
  schemas: {}
